[package]
name = "stacks"
version = "0.1.0"
authors = ["JackRedstonia <jackredstonia64@gmail.com>"]
edition = "2018"
build = "build.rs"
repository = "https://gitlab.com/JackRedstonia/stacks"
exclude = ["./examples"]
readme = "../README.md"
license = "MPL2.0"

[profile.release]
lto = "thin"

[dependencies]
skulpin-renderer = "0.5"
skulpin-renderer-sdl2 = "0.5"
unsafe-any = "*"

[dependencies.soloud]
git = "https://gitlab.com/JackRedstonia/soloud-rs"
