[package]
name = "stacks"
version = "0.1.0"
authors = ["JackRedstonia <jackredstonia64@gmail.com>"]
edition = "2018"
build = "build.rs"

[profile.release]
lto = "thin"

[dependencies]
skulpin-renderer = "0.5"
skulpin-renderer-sdl2 = "0.5"