[package]
name = "stacks"
version = "0.1.0"
authors = ["JackRedstonia <jackredstonia64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skulpin = { version = "0", default-features = false, features = ["skia_complete", "skulpin_winit"] }

[dev-dependencies]
