[package]
name = "stacks"
version = "0.1.0"
authors = ["reverb"]
edition = "2018"

[profile.release]
lto = "thin"

[dependencies]
skulpin-renderer = "0.5"
skulpin-renderer-winit = { version = "0.5", features = ["winit-latest"] }
