[package]
name = "stacks"
version = "0.1.0"
authors = ["JackRedstonia <jackredstonia64@gmail.com>"]
edition = "2018"
build = "build.rs"
repository = "https://gitlab.com/JackRedstonia/stacks"
exclude = ["./examples"]
readme = "../README.md"
license = "MIT"

[profile.release]
lto = "thin"

[dependencies]
skulpin-renderer-sdl2 = "0.5"
unsafe-any = "*"
unicode-linebreak = "0.1"

[dependencies.skulpin-renderer]
version = "0.5"
default-features = false
features = ["svg"]

[dependencies.soloud]
git = "https://gitlab.com/JackRedstonia/soloud-rs"
